### ISSUE TITLE
Code not formatted properly

### ISSUE THREAD

**Issue by kianenigma** [Chondria/SiB#3]
The code snippets in https://polkadot.study/tutorials/substrate-in-bits/docs/accessing-storage-and-functions-across-pallets are often not formatted. Quite a low hanging fruit. Also, pasting actaul logs is probably better suited than a screenshot :)

**Comment by abdbee** [comment]
Hi, Thanks Kian. I'll review the formating of the code snippets, replace the screenshot log with a text log and push a fix.
